name: 10.0.x

on:
  schedule:
    - cron: '0 0 * * SAT'
  workflow_dispatch:
    branches:
      - master

jobs:
  retro64:
    uses: vanilla-dpup/woof-CE/.github/workflows/build.yml@vanilladpup-10.0.x
    with:
      repo: vanilla-dpup/woof-CE
      ref: vanilladpup-10.0.x
      name: "Vanilla Dpup"
      version: 10.0.${{ github.run_number }}
      arch: x86_64
      compat-distro: debian
      compat-distro-version: bookworm64
      kernel: debian-bullseye
      prefix: vanilladpup
      artifact: vanilladpup-x86_64-10.0.${{ github.run_number }}-retro
      retention: 1
      variant: retro
  xorg64:
    uses: vanilla-dpup/woof-CE/.github/workflows/build.yml@vanilladpup-10.0.x
    with:
      repo: vanilla-dpup/woof-CE
      ref: vanilladpup-10.0.x
      name: "Vanilla Dpup"
      version: 10.0.${{ github.run_number }}
      arch: x86_64
      compat-distro: debian
      compat-distro-version: bookworm64
      kernel: debian-bookworm
      prefix: vanilladpup
      artifact: vanilladpup-x86_64-10.0.${{ github.run_number }}-xorg
      retention: 1
      variant: xorg
  xwayland64:
    uses: vanilla-dpup/woof-CE/.github/workflows/build.yml@vanilladpup-10.0.x
    with:
      repo: vanilla-dpup/woof-CE
      ref: vanilladpup-10.0.x
      name: "Vanilla Dpup"
      version: 10.0.${{ github.run_number }}
      arch: x86_64
      compat-distro: debian
      compat-distro-version: bookworm64
      kernel: debian-bookworm
      prefix: vanilladpup
      artifact: vanilladpup-x86_64-10.0.${{ github.run_number }}-xwayland
      retention: 1
      variant: xwayland
  dwl64:
    uses: vanilla-dpup/woof-CE/.github/workflows/build.yml@vanilladpup-10.0.x
    with:
      repo: vanilla-dpup/woof-CE
      ref: vanilladpup-10.0.x
      name: "Vanilla Dpup"
      version: 10.0.${{ github.run_number }}
      arch: x86_64
      compat-distro: debian
      compat-distro-version: bookworm64
      prefix: vanilladpup
      kernel: debian-bookworm
      artifact: vanilladpup-x86_64-10.0.${{ github.run_number }}-dwl
      retention: 1
      variant: dwl
  retro32:
    uses: vanilla-dpup/woof-CE/.github/workflows/build.yml@vanilladpup-10.0.x
    with:
      repo: vanilla-dpup/woof-CE
      ref: vanilladpup-10.0.x
      name: "Vanilla Dpup"
      version: 10.0.${{ github.run_number }}
      arch: x86
      compat-distro: debian
      compat-distro-version: bookworm
      kernel: debian-bullseye
      prefix: vanilladpup
      artifact: vanilladpup-x86-10.0.${{ github.run_number }}-retro
      retention: 1
      variant: retro
  upload:
    needs: [retro64, xorg64, xwayland64, dwl64, retro32]
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - arch: x86_64
            variant: dwl
          - arch: x86_64
            variant: xwayland
          - arch: x86_64
            variant: xorg
          - arch: x86_64
            variant: retro
          - arch: x86
            variant: retro
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: vanilladpup-${{ matrix.arch }}-10.0.${{ github.run_number }}-${{ matrix.variant }}
          path: .
      - name: Rename ISO
        run: mv -f *.iso vanilladpup-10.0.${{ github.run_number }}-${{ matrix.variant }}.iso
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: vanilladpup-${{ matrix.arch }}-10.0.${{ github.run_number }}-${{ matrix.variant }}
          tag_name: vanilladpup-${{ matrix.arch }}-10.0.${{ github.run_number }}-${{ matrix.variant }}
          fail_on_unmatched_files: true
          files: |
            *.iso
            kernel_sources-*.sfs
  cleanup:
    needs: upload
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - arch: x86_64
            keep: 4
          - arch: x86
            keep: 1
    steps:
      - name: Delete old ${{ matrix.arch }} releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: ${{ matrix.keep }}
          delete_tag_pattern: vanilladpup-${{ matrix.arch }}-10.0.
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
