name: 11.0.x

on:
  schedule:
    - cron: '0 0 * * SAT'
  workflow_dispatch:
    branches:
      - master

jobs:
  labwc64:
    uses: vanilla-dpup/woof-CE/.github/workflows/build.yml@vanilladpup-11.0.x
    with:
      repo: vanilla-dpup/woof-CE
      ref: vanilladpup-11.0.x
      name: "Vanilla Dpup"
      version: 11.0.${{ github.run_number }}
      arch: x86_64
      compat-distro: debian
      compat-distro-version: sid64
      kernel: debian-sid
      prefix: vanilladpup
      artifact: vanilladpup-x86_64-11.0.${{ github.run_number }}-labwc
      retention: 1
  upload64:
    needs: [labwc64]
    runs-on: ubuntu-20.04
    steps:
      - name: Download labwc build artifact
        uses: actions/download-artifact@v3
        with:
          name: vanilladpup-x86_64-11.0.${{ github.run_number }}-labwc
          path: labwc
      - name: Rename ISO
        run: |
          mv -f labwc/*-bios.img.gz vanilladpup-11.0.${{ github.run_number }}-labwc-bios.img.gz
          mv -f labwc/*-uefi.img.gz vanilladpup-11.0.${{ github.run_number }}-labwc-uefi.img.gz
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: vanilladpup-x86_64-11.0.${{ github.run_number }}
          tag_name: vanilladpup-x86_64-11.0.${{ github.run_number }}
          fail_on_unmatched_files: true
          files: |
            *.img.gz
            labwc/kernel_sources-*.sfs
  cleanup:
    needs: [upload64]
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch: [x86_64]
    steps:
      - name: Delete old ${{ matrix.arch }} releases
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          keep_latest: 1
          delete_tag_pattern: vanilladpup-${{ matrix.arch }}-11.0.
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
