name: 9.3.x

on:
  workflow_dispatch:
    branches:
      - master

jobs:
  x86_64:
    uses: vanilla-dpup/woof-CE/.github/workflows/build.yml@vanilladpup-10.0.x
    with:
      repo: vanilla-dpup/woof-CE
      ref: vanilladpup-10.0.x
      name: "Vanilla Dpup"
      version: 9.3.0-beta${{ github.run_number }}
      arch: x86_64
      compat-distro: debian
      compat-distro-version: bullseye64
      kernel: debian-bullseye
      prefix: vanilladpup
      artifact: vanilladpup-x86_64-9.3.0-beta${{ github.run_number }}
      retention: 1
  x86:
    uses: vanilla-dpup/woof-CE/.github/workflows/build.yml@vanilladpup-10.0.x
    with:
      repo: vanilla-dpup/woof-CE
      ref: vanilladpup-10.0.x
      name: "Vanilla Dpup"
      version: 9.3.0-beta${{ github.run_number }}
      arch: x86
      compat-distro: debian
      compat-distro-version: bullseye
      kernel: debian-bullseye
      prefix: vanilladpup
      artifact: vanilladpup-x86-9.3.0-beta${{ github.run_number }}
      retention: 1
  upload:
    needs: [x86_64, x86]
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        arch: [x86_64, x86]
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: vanilladpup-${{ matrix.arch }}-9.3.0-beta${{ github.run_number }}
          path: .
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: vanilladpup-${{ matrix.arch }}-9.3.0-beta${{ github.run_number }}
          tag_name: vanilladpup-${{ matrix.arch }}-9.3.0-beta${{ github.run_number }}
          fail_on_unmatched_files: true
          files: |
            *.iso
            kernel_sources-*.sfs
  cleanup:
    needs: upload
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - arch: x86_64
            keep: 1
          - arch: x86
            keep: 1
    steps:
      - name: Delete old ${{ matrix.arch }} releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: ${{ matrix.keep }}
          delete_tag_pattern: vanilladpup-${{ matrix.arch }}-9.3.
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
